In [11]:
#1. Import the NUMPY package under the name np.
import numpy as np


In [5]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)
print(np.show_config())


1.17.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/emilio/miniconda3/envs/test_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/emilio/miniconda3/envs/test_env/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/emilio/miniconda3/envs/test_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/emilio/miniconda3/envs/test_env/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/emilio/miniconda3/envs/test_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/emilio/miniconda3/envs/test_env/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/emilio/miniconda3/envs/test_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/emilio/miniconda3/e

In [6]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

#4. Print a.

a = np.random.random((2,3,5))
print(a)

a = np.random.rand(2,3,5) 
print(a)

a = np.random.random_sample([2,3,5])
print(a)




[[[0.45049577 0.34474736 0.62976191 0.85584154 0.66008854]
  [0.51364124 0.81484741 0.94513154 0.78357197 0.48004015]
  [0.27475766 0.47079353 0.78387278 0.11046966 0.23143233]]

 [[0.14519188 0.11192417 0.90759261 0.6223111  0.30343874]
  [0.14232343 0.32824599 0.75077532 0.9103109  0.44001687]
  [0.14344877 0.35354041 0.50837063 0.91778484 0.50096657]]]
[[[0.14778902 0.30151522 0.4416763  0.36056014 0.96810611]
  [0.54680509 0.3811747  0.45965716 0.17847672 0.74633218]
  [0.31408097 0.76395654 0.17719351 0.47389445 0.89356284]]

 [[0.50152676 0.25275637 0.50901596 0.2962606  0.86673908]
  [0.88829536 0.15545224 0.16520923 0.89648905 0.10455079]
  [0.37193284 0.19944404 0.95936224 0.06921547 0.17330095]]]
[[[0.5010245  0.17787598 0.21194023 0.20646768 0.0814723 ]
  [0.39355625 0.10266434 0.48773791 0.53684782 0.71281753]
  [0.99813088 0.70128142 0.34456778 0.01200052 0.27997458]]

 [[0.77750022 0.740056   0.76545223 0.30603881 0.26940666]
  [0.1057901  0.33988497 0.43357153 0.57881466

In [9]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

#6. Print b.

b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
#7. Do a and b have the same size? How do you prove that in Python code?
